sudo: false
 
language: node_js
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
 
branches:
  only:
    - eslint
 
before_script:
  - meteor npm install
 
script:
  - npm run build:travis

deploy:
  provider: releases
  user: GITHUB_LOGIN
  password: GITHUB_PASSWORD
  file: "../OGV-meteor.tar.gz"
  skip_cleanup: true
  on:
    branch: eslint
    tags: true